name: Create PR on Workflow Completion Event

on:
  repository_dispatch:
    types: [workflow_completed]

jobs:
  create-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get Latest Commit SHA
        id: get_sha
        run: echo "::set-output name=sha::$(git rev-parse HEAD)"

      - name: Create New Branch
        run: |
          curl -X POST \
            -H "Authorization: token ${{ secrets.PERSONAL_ACCESS_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/git/refs \
            -d '{"ref": "refs/heads/new-feature-branch", "sha": "${{ steps.get_sha.outputs.sha }}"}'

      - name: Make a Commit in New Branch
        run: |
          git checkout new-feature-branch
          echo "This is an automated commit" >> file.txt
          git add file.txt
          git commit -m "Automated commit to new-feature-branch"
          git push origin new-feature-branch

      - name: Create Pull Request
        run: |
          curl -X POST \
            -H "Authorization: token ${{ secrets.PERSONAL_ACCESS_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/pulls \
            -d '{
              "title": "Automated PR for workflow completion",
              "head": "new-feature-branch",
              "base": "main",
              "body": "This PR is triggered automatically after the workflow is completed in the source repo."
            }'
