name: Create PR with Unique Branch Name

on:
  repository_dispatch:
    types: [workflow_completed]

jobs:
  create-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get Latest Commit SHA
        id: get_sha
        run: echo "::set-output name=sha::$(git rev-parse HEAD)"

      - name: Generate Random Branch Name
        id: generate_branch
        run: |
          BRANCH_NAME="new-feature-branch-$(date +%s)"
          echo "Branch Name: $BRANCH_NAME"
          echo "::set-output name=branch_name::$BRANCH_NAME"

      - name: Create New Branch
        run: |
          curl -X POST \
            -H "Authorization: token ${{ secrets.PERSONAL_ACCESS_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/git/refs \
            -d '{"ref": "refs/heads/${{ steps.generate_branch.outputs.branch_name }}", "sha": "${{ steps.get_sha.outputs.sha }}"}'

      - name: Fetch Remote Branches
        run: |
          git fetch origin

      - name: Set Git User Information
        run: |
          git config --global user.email "mahmoudabozeed56@gmail.com"
          git config --global user.name "MahmoudAbuzeed"

      - name: Check Out or Create Branch
        run: |
          git checkout ${{ steps.generate_branch.outputs.branch_name }} || git checkout -b ${{ steps.generate_branch.outputs.branch_name }}

      - name: Make a Commit in New Branch
        run: |
          echo "This is an automated commit" >> file.txt
          git add file.txt
          git commit -m "Automated commit to ${{ steps.generate_branch.outputs.branch_name }}"
          git push origin ${{ steps.generate_branch.outputs.branch_name }}

      - name: Create Pull Request
        run: |
          curl -X POST \
            -H "Authorization: token ${{ secrets.PERSONAL_ACCESS_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/pulls \
            -d '{
              "title": "Automated PR for workflow completion",
              "head": "'${{ steps.generate_branch.outputs.branch_name }}'",
              "base": "main",
              "body": "This PR is triggered automatically after the workflow is completed in the source repo."
            }'
