name: Create PR on Workflow Completion Event

on:
  repository_dispatch:
    types: [workflow_completed]

jobs:
  create-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create Pull Request
        run: |
          curl -X POST \
            -H "Authorization: token ${{ secrets.PERSONAL_ACCESS_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/pulls \
            -d '{
              "title": "Automated PR for workflow completion",
              "head": "new-feature-branch",
              "base": "main",
              "body": "This PR is triggered automatically after the workflow is completed in the source repo."
            }'
